version: '3.7'

secrets:
  MY_SQL_PASSWORD:
    external: true

services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    secrets:
      - MY_SQL_PASSWORD
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_DATABASE=petclinic
      - MYSQL_PASSWORD_FILE=/run/secrets/MY_SQL_PASSWORD
      - MYSQL_HOST=%
    volumes:
      # - ./Docker/db_data:/var/lib/mysql
      - ./Docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./Docker/mysql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    logging:
      driver: gcplogs
      options:
        gcp-project: gd-gcp-internship-kha-koh

  petclinic:
    image: spring-petclinic-swarm
    depends_on:
      - mysql
    secrets:
      - MY_SQL_PASSWORD
    environment:
      - MY_SQL_PROFILE=mysql
      - MY_SQL_URL=mysql
      - MY_SQL_PORT=3306
      - MY_SQL_USERNAME=petclinic
      - MY_SQL_DB_NAME=petclinic
    deploy:
      replicas: 3
    logging:
      driver: gcplogs
      options:
        gcp-project: gd-gcp-internship-kha-koh


  nginx:
    image: nginx:stable-perl
    depends_on:
      - petclinic
    ports:
      - "18080:80"
    volumes:
      - ./Docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    deploy:
      replicas: 1
    logging:
      driver: gcplogs
      options:
        gcp-project: gd-gcp-internship-kha-koh
